# Generated by Django 5.2.7 on 2026-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
